//! Traits for namespace tags and GID conversion.
//!
//! These traits are implemented by types generated from the `namespace!` macro,
//! enabling zero-cost conversion from typed tags to GID.

use crate::registry::NamespaceRegistry;
use crate::GID;

/// A compile-time namespace tag, generated by the `namespace!` macro.
///
/// Each node in the namespace tree gets a zero-sized Tag type with
/// associated constants for path, depth, and stable GID.
///
/// ```rust,ignore
/// namespace! {
///     pub mod ids {
///         Movement { Idle; Running; }
///     }
/// }
///
/// // Generated:
/// // ids::Movement::Idle::Tag implements NamespaceTag
/// // ids::Movement::Idle::Tag::PATH  = "Movement.Idle"
/// // ids::Movement::Idle::Tag::DEPTH = 1
/// // ids::Movement::Idle::Tag::GID   = 0x... (const hierarchical hash)
/// ```
pub trait NamespaceTag: Copy + 'static {
    /// Full dot-separated path, e.g. `"Movement.Idle"`.
    const PATH: &'static str;

    /// Depth in the tree (0 = top-level).
    const DEPTH: u8;

    /// Stable hierarchical GID, computed at compile time.
    ///
    /// This is a `const` value — no registry lookup needed.
    const STABLE_GID: GID;

    /// Get the GID. This is just `Self::STABLE_GID` but useful
    /// when you have a value (not just the type).
    #[inline]
    fn gid() -> GID {
        Self::STABLE_GID
    }
}

// =============================================================================
// IntoGid — uniform conversion to GID
// =============================================================================

/// Convert to GID. Implemented for raw `GID` (passthrough) and all `NamespaceTag` types.
pub trait IntoGid: Copy {
    fn into_gid(self) -> GID;
}

impl IntoGid for GID {
    #[inline]
    fn into_gid(self) -> GID {
        self
    }
}

impl<T: NamespaceTag> IntoGid for T {
    #[inline]
    fn into_gid(self) -> GID {
        T::STABLE_GID
    }
}

// =============================================================================
// IntoGidWithRegistry — for contexts with a local (non-global) registry
// =============================================================================

/// Convert to GID using a specific registry instance.
///
/// Useful for ECS integrations where the registry is a `Res<NamespaceRegistry>`.
pub trait IntoGidWithRegistry: Copy {
    fn into_gid_with(self, registry: &NamespaceRegistry) -> GID;
}

impl IntoGidWithRegistry for GID {
    #[inline]
    fn into_gid_with(self, _registry: &NamespaceRegistry) -> GID {
        self
    }
}

impl<T: NamespaceTag> IntoGidWithRegistry for T {
    #[inline]
    fn into_gid_with(self, _registry: &NamespaceRegistry) -> GID {
        // Tag already knows its GID at compile time
        T::STABLE_GID
    }
}

// =============================================================================
// IntoGids — batch conversion
// =============================================================================

/// Convert a collection of items into a `Vec<GID>`.
pub trait IntoGids {
    fn into_gids(self) -> Vec<GID>;
}

impl<T: IntoGid> IntoGids for Vec<T> {
    #[inline]
    fn into_gids(self) -> Vec<GID> {
        self.into_iter().map(IntoGid::into_gid).collect()
    }
}

// Tuple impls for ergonomic multi-id passing
impl<A: IntoGid, B: IntoGid> IntoGids for (A, B) {
    #[inline]
    fn into_gids(self) -> Vec<GID> {
        vec![self.0.into_gid(), self.1.into_gid()]
    }
}

impl<A: IntoGid, B: IntoGid, C: IntoGid> IntoGids for (A, B, C) {
    #[inline]
    fn into_gids(self) -> Vec<GID> {
        vec![
            self.0.into_gid(),
            self.1.into_gid(),
            self.2.into_gid(),
        ]
    }
}

impl<A: IntoGid, B: IntoGid, C: IntoGid, D: IntoGid> IntoGids for (A, B, C, D) {
    #[inline]
    fn into_gids(self) -> Vec<GID> {
        vec![
            self.0.into_gid(),
            self.1.into_gid(),
            self.2.into_gid(),
            self.3.into_gid(),
        ]
    }
}

// Const array support
impl<T: IntoGid, const N: usize> IntoGids for [T; N] {
    #[inline]
    fn into_gids(self) -> Vec<GID> {
        self.into_iter().map(IntoGid::into_gid).collect()
    }
}